### ISSUE TITLE
BG3ModdingUtil closes after clicking Vanilla or Modded. No success message

### ISSUE THREAD

**Issue by Spiky652** [sixstepsaway/BG3-Modding-Util#5]
Hello,

I've tried following the steps shown in the slides but maybe I'm missing something? When I did a util test by pressing either the Vanilla or Modded button, it just closes without showing a success message. And all symlinked mods are not shown in the appdata folder.
 
Do you have any suggestions on how to identify the problem and what it could be?

Thanks so much.

**Comment by Spiky652** [comment]
Here's what I have so far

![Screenshot_1](https://github.com/sixstepsaway/BG3-Modding-Util/assets/155275522/ab25b24e-099b-4be8-98d0-3efff7735e12)

![Screenshot_2](https://github.com/sixstepsaway/BG3-Modding-Util/assets/155275522/245bf68f-8dc2-4035-a7bd-94ba8db9a908)

![Screenshot_3](https://github.com/sixstepsaway/BG3-Modding-Util/assets/155275522/9f031f6e-f8f0-44b0-b280-d9a840910264)

![Screenshot_4](https://github.com/sixstepsaway/BG3-Modding-Util/assets/155275522/bb184534-ab4e-4d4f-9fb1-cd20f742cb6e)

**Comment by sixstepsaway** [comment]
Hello! Can you check/confirm you're running the app as an administrator? That you have administrator permissions on your computer?

**Comment by Spiky652** [comment]
Hi, yes. I was able to run the app as an administrator but the same problem persists.

**Comment by Jonah-Thomas** [comment]
I am also getting the same issue.

**Comment by JadeWinters** [comment]
I’m also not getting any success message

**Comment by DravenFrostfall** [comment]
Exactly the same issue for me. The program just crashes with no errors or .log file created. Running as admin doesn't help.
I'm running the GOG version of the game if that help with the latest Hotfix (#19).

**Comment by aehallh** [comment]
I am having the same exact issue when I tried this on my daughter's computer. No issues with mine, or with the other installs/setups I have done or helped people with. Just her computer, and I can't figure it out. Went through all the troubleshooting I could find (including running it as administrator of course), and found no solution.  When either vanilla or modded are pressed, it simply shuts down/crashes with no sort of error displayed to point the way to what the issue might be.

**Comment by Jellie188** [comment]
So I know this might sound stupid but any other characters in your bg3config file will create an error, whether that be a space after the route to the game or a line break / enter key press. Just resolved the issue with a friend that way by deleting a followed line after he pasted his games location in to the config.

**Comment by Blindasaurus** [comment]
I had this problem ever since putting Level 20 (Multiclass) in /gameData . 

It crashed with this log 

"Caught exception making junction: Public
Exception: Cannot create 'I:\SteamLibrary\steamapps\common\Baldurs Gate 3\Data\Public' because a file or directory with the same name already exists.
Exception Message: Cannot create 'I:\SteamLibrary\steamapps\common\Baldurs Gate 3\Data\Public' because a file or directory with the same name already exists.
Exception Source: System.Private.CoreLib
Inner Exception: 
Base Exception: System.IO.IOException: Cannot create 'I:\SteamLibrary\steamapps\common\Baldurs Gate 3\Data\Public' because a file or directory with the same name already exists.
   at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
   at System.IO.Directory.CreateSymbolicLink(String path, String pathToTarget)
   at SSA.VirtualFileSystem.VFileSystem.MakeJunction(String Original, String Destination) in I:\Code\C#\BG3 Modding Utility\src\utilities\VirtualFileSystem.cs:line 132
Exception Data: System.Collections.ListDictionaryInternal
Exception Stack Trace:    at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
   at System.IO.Directory.CreateSymbolicLink(String path, String pathToTarget)
   at SSA.VirtualFileSystem.VFileSystem.MakeJunction(String Original, String Destination) in I:\Code\C#\BG3 Modding Utility\src\utilities\VirtualFileSystem.cs:line 132
Items in Location:
       Folder: Shared
       Symlink: False
       Folder: SharedDev
       Symlink: False"
       
and now it just closes without doing anything if I click the "Vanilla" or the "Modded" button and deleting Level 20 (Multiclass) from the directory didn't help.

**Comment by mike10101011** [comment]
I too have this issue even with a fresh install. The folder path in the config file is correct and does not have any extra characters.
